package com.iplfreaks.common;

public enum Keys {
	FIXTURES, 
	TEAM, 
	FIXTURE_CHALLENGES, 
	CAN_EDIT_CHALLENGE, 
	CHALLENGER_NAME, 
	CHALLENGER_EMAIL, 
	PREDICTION, 
	CHALLENGERS, 
	PENDING_CHALLENGERS, 
	USER_LEAGUES, 
	FIXTURE_SCORE, LEAGUE_SCORE
}
