db = connect("localhost:27017/sports_on_net_1", "gambler", "gambler");

db.team.insert({"name":"Mumbai Indians (MI)", "homeCity":"Mumbai", "country":"India", "homeVenue":"Wankhede Stadium , DY Patil Stadium"});
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Rohit Sharma (c)", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Lasith Malinga", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Harbhajan Singh", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Ambati Rayudu", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Kieron Pollard", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Michael Hussey", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Corey Anderson", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Pragyan Ojha", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Zaheer Khan", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Aditya Tare", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Jasprit Bumrah", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Jalaj Saxena", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Josh Hazlewood", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Marchant De Lange", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Krismar Santokie", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Ben Dunk", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"C.M. Gautam", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Apoorv Vijay Wankhade", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Pawan Suyal", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Sushant Marathe", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"Players":{"playerName":"Shreyas Gopal", "skill":"ALL-ROUNDER"}}}, false, false);

db.team.insert({"name":"Chennai Super Kings (CSK)", "homeCity":"Chennai", "country":"India", "homeVenue":"M. A. Chidambaram Stadium"});
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"MS Dhoni (c)", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Ravindra Jadeja", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Ravichandran Ashwin", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Dwayne Bravo", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Suresh Raina", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Faf Du Plessis", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Dwayne Smith", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Brendon McCullum", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Ashish Nehra", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Mohit Sharma", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Ishwar Chandra Pandey", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Ben Hilfenhaus", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"John Hastings", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Samuel Badree", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Matt Henry", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Mithun Manhas", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Vijay Shankar", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Ronit More", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Baba Aparajith", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"Players":{"playerName":"Pawan Negi", "skill":"BOWLER"}}}, false, false);

db.team.insert({"name":"Rajasthan Royals (RR)", "homeCity":"Jaipur", "country":"India", "homeVenue":"Sawai Mansingh Stadium"});
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Shane Watson (c)", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"James Faulkner", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Stuart Binny", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Ajinkya Rahane", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Sanju Samson", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Steve Smith", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Brad Hodge", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Rajat Bhatia", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Tim Southee", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Dhawal Kulkarni", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Abhishek Nayar", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Kane Richardson", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Ben Cutting", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Karun Nair", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Unmukt Chand", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Iqbal Abdullah", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Deepak Hooda", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Dishant Yagnik", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Kevon Cooper", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Vikramjeet Malik", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Ankit Nagendra Sharma", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Rahul Tewatia", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Ankush Bains", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Amit Mishra", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"Players":{"playerName":"Pravin Tambe", "skill":"BOWLER"}}}, false, false);

db.team.insert({"name":"Sunrisers Hyderabad (SH)", "homeCity":"Hyderabad", "country":"India", "homeVenue":"Rajiv Gandhi International Cricket Stadium"});
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Shikhar Dhawan (c)", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Dale Steyn", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"David Warner", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Amit Mishra", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Bhuvneshwar Kumar", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Aaron Finch", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Karn Sharma", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Darren Sammy", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Ishant Sharma", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Irfan Pathan", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Moises Henriques", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"K Lokesh Rahul", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Parveez Rasool", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Jason Holder", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Venugopal Rao", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Naman Ojha", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Brendan Taylor", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Prasanth Parameswaran", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Amit Paunikar", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Ashish Reddy", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Srikkanth Anirudha", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Ricky Bhui", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Chama Milind", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"Players":{"playerName":"Manprit Juneja", "skill":"BATSMAN"}}}, false, false);

db.team.insert({"name":"Royal Challengers Bangalore (RCB)", "homeCity":"Bengaluru", "country":"India", "homeVenue":"M. Chinnaswamy Stadium"});
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Virat Kohli (c)", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Chris Gayle", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"AB De Villiers", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Yuvraj Singh", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Mitchell Starc", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Albie Morkel", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Varun Aaron", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Ashok Dinda", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Parthiv Patel", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Muttiah Muralitharan", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Ravi Rampaul", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Nic Maddinson", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Harshal Patel", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Vijay Zol", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Abu Nechim Ahmed", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Sachin Rana", "skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Shadab Jakati", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Sandeep Warrier", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Tanmay Mishra", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Yogesh Takawale", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"Players":{"playerName":"Yuzvendra Singh Chahal", "skill":"BOWLER"}}}, false, false);

db.team.insert({"name":"Kolkata Knight Riders (KKR)", "homeCity":"Kolkata", "country":"India", "homeVenue":"Eden Gardens"});
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Gautam Gambhir (c)","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Sunil Narine","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Jacques Kallis","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Robin Uthappa","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Piyush Chawla","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Yusuf Pathan","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Shakib Al Hasan","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Morne Morkel","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Vinay Kumar","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Umesh Yadav","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Manish Pandey","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Chris Lynn","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Patrick Cummins","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Ryan Ten Doeschate","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Suryakumar Yadav","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Andre Russell","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Manvinder Bisla","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Veer Pratap Singh","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Kuldeep Singh Yadav","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Debabrata Das","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"Players":{"playerName":"Sayan Sekhar Mandal","skill":"BOWLER"}}}, false, false);

db.team.insert({"name":"Kings XI Punjab (KXIP)", "homeCity":"Mohali", "country":"India", "homeVenue":"PCA Stadium, Mohali , HPCA Stadium, Dharamsala"});
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Manan Vohra","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"David Miller","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Mitchell Johnson","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Glenn Maxwell","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"George Bailey (c)","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Virender Sehwag","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Rishi Dhawan","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Wriddhiman Saha","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Shaun Marsh","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Cheteshwar Pujara","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Beuran Hendricks","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Lakshmipathy Balaji","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Thisara Perera","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Gurkirat Singh Mann","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Murali Kartik","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Sandeep Sharma","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Mandeep Hardev Singh","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Akshar Rajesh Patel","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Parvinder Awana","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Shardul Narendra Thakur","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Anureet Singh","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Shivam Sharma","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"Players":{"playerName":"Karanveer Singh","skill":"BOWLER"}}}, false, false);

db.team.insert({"name":"Delhi Daredevils (DD)", "homeCity":"New Delhi", "country":"India", "homeVenue":"Feroz Shah Kotla , Raipur International Cricket Stadium"});
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Dinesh Karthik","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Kevin Pietersen (c)","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Murali Vijay","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Mohammad Shami","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Nathan Coulter-Nile","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Quinton De Kock","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Manoj Tiwary","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Jaydev Unadkat","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Jean-Paul Duminy","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Ross Taylor","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Kedar Jadhav","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Rahul Sharma","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Mayank Agarwal","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Laxmi Ratan Shukla","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Jimmy Neesham","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Wayne Parnell","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Shahbaz Nadeem","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Saurabh Tiwary","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Siddarth Kaul","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Rahul Shukla","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Jayant Yadav","skill":"ALL-ROUNDER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"HS Sharath","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"Players":{"playerName":"Milind Kumar","skill":"BATSMAN"}}}, false, false);











