db = connect("localhost:27017/sports_on_net_1", "gambler", "gambler");

db.team.insert({"name":"Mumbai Indians (MI)", "homeCity":"Mumbai", "country":"India", "homeVenue":"Wankhede Stadium , DY Patil Stadium"});
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Rohit Sharma (c)", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Lasith Malinga", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Harbhajan Singh", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Ambati Rayudu", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Kieron Pollard", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Michael Hussey", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Corey Anderson", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Pragyan Ojha", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Zaheer Khan", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Aditya Tare", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Jasprit Bumrah", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Jalaj Saxena", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Josh Hazlewood", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Marchant De Lange", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Krismar Santokie", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Ben Dunk", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"C.M. Gautam", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Apoorv Vijay Wankhade", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Pawan Suyal", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Sushant Marathe", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Mumbai Indians (MI)"},{"$addToSet":{"players":{"name":"Shreyas Gopal", "skill":"ALLROUNDER"}}}, false, false);

db.team.insert({"name":"Chennai Super Kings (CSK)", "homeCity":"Chennai", "country":"India", "homeVenue":"M. A. Chidambaram Stadium"});
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"MS Dhoni (c)", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Ravindra Jadeja", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Ravichandran Ashwin", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Dwayne Bravo", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Suresh Raina", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Faf Du Plessis", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Dwayne Smith", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Brendon McCullum", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Ashish Nehra", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Mohit Sharma", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Ishwar Chandra Pandey", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Ben Hilfenhaus", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"John Hastings", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Samuel Badree", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Matt Henry", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Mithun Manhas", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Vijay Shankar", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Ronit More", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Baba Aparajith", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Chennai Super Kings (CSK)"},{"$addToSet":{"players":{"name":"Pawan Negi", "skill":"BOWLER"}}}, false, false);

db.team.insert({"name":"Rajasthan Royals (RR)", "homeCity":"Jaipur", "country":"India", "homeVenue":"Sawai Mansingh Stadium"});
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Shane Watson (c)", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"James Faulkner", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Stuart Binny", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Ajinkya Rahane", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Sanju Samson", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Steve Smith", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Brad Hodge", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Rajat Bhatia", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Tim Southee", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Dhawal Kulkarni", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Abhishek Nayar", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Kane Richardson", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Ben Cutting", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Karun Nair", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Unmukt Chand", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Iqbal Abdullah", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Deepak Hooda", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Dishant Yagnik", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Kevon Cooper", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Vikramjeet Malik", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Ankit Nagendra Sharma", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Rahul Tewatia", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Ankush Bains", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Amit Mishra", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Rajasthan Royals (RR)"},{"$addToSet":{"players":{"name":"Pravin Tambe", "skill":"BOWLER"}}}, false, false);

db.team.insert({"name":"Sunrisers Hyderabad (SH)", "homeCity":"Hyderabad", "country":"India", "homeVenue":"Rajiv Gandhi International Cricket Stadium"});
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Shikhar Dhawan (c)", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Dale Steyn", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"David Warner", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Amit Mishra", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Bhuvneshwar Kumar", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Aaron Finch", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Karn Sharma", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Darren Sammy", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Ishant Sharma", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Irfan Pathan", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Moises Henriques", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"K Lokesh Rahul", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Parveez Rasool", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Jason Holder", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Venugopal Rao", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Naman Ojha", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Brendan Taylor", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Prasanth Parameswaran", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Amit Paunikar", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Ashish Reddy", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Srikkanth Anirudha", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Ricky Bhui", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Chama Milind", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Sunrisers Hyderabad (SH)"},{"$addToSet":{"players":{"name":"Manprit Juneja", "skill":"BATSMAN"}}}, false, false);

db.team.insert({"name":"Royal Challengers Bangalore (RCB)", "homeCity":"Bengaluru", "country":"India", "homeVenue":"M. Chinnaswamy Stadium"});
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Virat Kohli (c)", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Chris Gayle", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"AB De Villiers", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Yuvraj Singh", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Mitchell Starc", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Albie Morkel", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Varun Aaron", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Ashok Dinda", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Parthiv Patel", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Muttiah Muralitharan", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Ravi Rampaul", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Nic Maddinson", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Harshal Patel", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Vijay Zol", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Abu Nechim Ahmed", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Sachin Rana", "skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Shadab Jakati", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Sandeep Warrier", "skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Tanmay Mishra", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Yogesh Takawale", "skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Royal Challengers Bangalore (RCB)"},{"$addToSet":{"players":{"name":"Yuzvendra Singh Chahal", "skill":"BOWLER"}}}, false, false);

db.team.insert({"name":"Kolkata Knight Riders (KKR)", "homeCity":"Kolkata", "country":"India", "homeVenue":"Eden Gardens"});
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Gautam Gambhir (c)","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Sunil Narine","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Jacques Kallis","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Robin Uthappa","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Piyush Chawla","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Yusuf Pathan","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Shakib Al Hasan","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Morne Morkel","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Vinay Kumar","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Umesh Yadav","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Manish Pandey","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Chris Lynn","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Patrick Cummins","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Ryan Ten Doeschate","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Suryakumar Yadav","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Andre Russell","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Manvinder Bisla","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Veer Pratap Singh","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Kuldeep Singh Yadav","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Debabrata Das","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kolkata Knight Riders (KKR)"},{"$addToSet":{"players":{"name":"Sayan Sekhar Mandal","skill":"BOWLER"}}}, false, false);

db.team.insert({"name":"Kings XI Punjab (KXIP)", "homeCity":"Mohali", "country":"India", "homeVenue":"PCA Stadium, Mohali , HPCA Stadium, Dharamsala"});
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Manan Vohra","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"David Miller","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Mitchell Johnson","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Glenn Maxwell","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"George Bailey (c)","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Virender Sehwag","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Rishi Dhawan","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Wriddhiman Saha","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Shaun Marsh","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Cheteshwar Pujara","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Beuran Hendricks","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Lakshmipathy Balaji","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Thisara Perera","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Gurkirat Singh Mann","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Murali Kartik","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Sandeep Sharma","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Mandeep Hardev Singh","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Akshar Rajesh Patel","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Parvinder Awana","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Shardul Narendra Thakur","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Anureet Singh","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Shivam Sharma","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Kings XI Punjab (KXIP)"},{"$addToSet":{"players":{"name":"Karanveer Singh","skill":"BOWLER"}}}, false, false);

db.team.insert({"name":"Delhi Daredevils (DD)", "homeCity":"New Delhi", "country":"India", "homeVenue":"Feroz Shah Kotla , Raipur International Cricket Stadium"});
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Dinesh Karthik","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Kevin Pietersen (c)","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Murali Vijay","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Mohammad Shami","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Nathan Coulter-Nile","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Quinton De Kock","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Manoj Tiwary","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Jaydev Unadkat","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Jean-Paul Duminy","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Ross Taylor","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Kedar Jadhav","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Rahul Sharma","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Mayank Agarwal","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Laxmi Ratan Shukla","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Jimmy Neesham","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Wayne Parnell","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Shahbaz Nadeem","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Saurabh Tiwary","skill":"BATSMAN"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Siddarth Kaul","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Rahul Shukla","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Jayant Yadav","skill":"ALLROUNDER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"HS Sharath","skill":"BOWLER"}}}, false, false);
db.team.update({"name":"Delhi Daredevils (DD)"},{"$addToSet":{"players":{"name":"Milind Kumar","skill":"BATSMAN"}}}, false, false);











